---
- name: Fedora Workstation setup
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: DNF settings
      become: true
      file:
        src: "files/dnf.conf"
        dest: "/etc/dnf/dnf.conf"

    - name: Upgrade all packages
      become: true
      dnf:
        name: "*"
        state: latest

    - name: Run all the tasks
      include_tasks:
        - tasks/repos.yml
        - tasks/packages.yml
        - tasks/flatpak.yml
        - tasks/fish.yml
        - tasks/system.yml
        - tasks/services.yml
        - tasks/gnome.yml
        - tasks/python.yml
