---
- name: Install Golang
  dnf:
    name: golang
    state: present

- name: Create Go directory
  file:
    path: { { go_dir } }
    state: directory
    owner: { { user } }
    group: { { group } }

- name: Configure GOPATH
  shell: >
    set -U $GOPATH { { go_dir } }:{ { go_dev_dir } }
  args:
    executable: { { fish_shell_path } }
