---
- name: disable services related to evolution
  become: true
  systemd:
    masked: yes
    user: yes
    name: { { item } }
  with_items:
    - evolution-addressbook-factory.service
    - evolution-calendar-factory.service
    - evolution-source-registry.service
    - evolution-user-prompter.service
    - cups.service
    - avahi-daemon.service

- name: disable unwanted services
  become: true
  systemd:
    state: disabled
    name: { { item } }
  with_items:
    - tracker-store
    - gvfs-goa-volume-monitor

- name: enable fstrim
  become: true
  systemd:
    state: enabled
    name: fstrim.timer
