---
- name: Create a user for work related usage.
  user:
    name: Work
    comment: user for work related usage
    password: "$6$HEu.SbtXrbKF2kLj$v3CWlQH0uI/ZW3EnOgrXmPXB7aEWaBhZXes0vaOXuLfeF.KkrGOUxNMzzvLkciNjRtK4dXmtiYOgQ/E5yS9D2/"
    shell: /bin/fish
    state: present

- name: Night Light settings
  block:
    - name: Enable Night Light
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: true
        state: present

    - name: Set Night Light Temperature
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
        value: uint32 4991
        state: present

    - name: Set Night Light Schedule From
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-from
        value: "18"
        state: present

    - name: Set Night Light Schedule To
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-to
        value: "7"
        state: present

- name: Install FiraCode iScript fonts
  block:
    - name: Create a directory for the fonts
      file:
        path: { { font_dir } }
        state: directory
      register: firacode

    - name: Copy FiraCode iScript fonts to root level font directory
      copy:
        src: { { item } }
        dest: { { firacode.stdout } }
      with_items:
        - files/FiraCodeiScript-Bold.ttf
        - files/FiraCodeiScript-Italic.ttf
        - files/FiraCodeiScript-Regular.ttf

    - name: Update font cache
      command: /usr/bin/fc-cache-64 -v

- name: Add Slack and GNOME Pomodoro to autostart.
  copy:
    src: { { item } }
    dest: { { autostart_dir } }
  with_items:
    - files/com.slack.Slack.desktop
    - files/org.gnome.Pomodoro.desktop

- name: Copy .gitconfig to user's home directory
  copy:
    src: files/gitconfig
    dest: "{ { home_dir } }/.gitconfig"

- name: Install argonaut theme for tilix
  command: wget -qO ~/.config/tilix/schemes/argonaut.json https://git.io/v7QV5

- name: Clear GNOME tracker cache file
  file:
    path: ~/.cache/tracker
    state: absent

- name: Install Starship
  command: "curl -fsSL https://starship.rs/install.sh | sudo bash"

- name: Change user shell to Fish
  become: true
  user:
    name: { { user } }
    shell: { { fish_shell_path } }

- name: config imwheel
  block:
    copy:
      src: "files/imwheel.service"
      dest: { { systemd_dir } }

    name: reload systemd configuration
    systemd:
      daemon_reload: yes
