---
- name: Copy .gitconfig to user's home directory
  copy:
    src: files/gitconfig
    dest: "{ { home_dir } }/.gitconfig"

- name: Change user shell to Fish
  become: true
  user:
    name: { { user } }
    shell: { { fish_shell_path } }

- name: Golang configuration
  block:
    - name: Create Go directory
      file:
        path: { { go_dir } }
        state: directory
        owner: { { user } }
        group: { { group } }

    - name: Configure GOPATH
      shell: >
        set -U $GOPATH { { go_dir } }:{ { go_dev_dir } }
      args:
        executable: { { fish_shell_path } }

- name: Install JetBrains Mono Font
  block:
    - get_url: >
        url= { { jetbrains_mono_url } }
        dest=/tmp/jetbrains-mono.zip

    - become: true
      unarchive:
        src: /tmp/jetbrains-mono.zip
        dest: /usr/share/fonts/
        remote_src: yes

    - command: fc-cache -v
