---
- name: Copy .gitconfig to user's home directory
  copy:
    src: files/gitconfig
    dest: "{ { home_dir } }/.gitconfig"

- name: Change user shell to Fish
  become: true
  user:
    name: { { user } }
    shell: { { fish_shell_path } }

- name: Golang configuration
  block:
    - name: Create Go directory
      file:
        path: { { go_dir } }
        state: directory
        owner: { { user } }
        group: { { group } }

    - name: Configure GOPATH
      shell: >
        set -U $GOPATH { { go_dir } }:{ { go_dev_dir } }
      args:
        executable: { { fish_shell_path } }

- name: Install fonts
  block:
    - name: Download fonts
      get_url: >
        url={ { item.key } }
        dest="/tmp/{ { item.value } }"
      with_items:
        - { key: jetbrains_mono_url, value: jetbrains-mono.zip }
        - { key: iosevka_url, value: iosevka.zip }
        - { key: iosevka_term_url, value: iosevka_term.zip }
        - { key: iosevka_aile_url, value: iosevka_aile.zip }

    - name: Copy fonts
      become: true
      unarchive:
        src: "/tmp/{ { item } }"
        dest: "/usr/share/fonts/"
        remote_src: yes
      with_items:
        - jetbrains-mono.zip
        - iosevka.zip
        - iosevka_term.zip
        - iosevka_aile.zip

    - command: fc-cache -v

- name: Configure Kitty terminal
  block:
    - file:
        src: files/kitty.conf
        dest: "~/.config/kitty/kitty.conf"

    - command: "curl { { item.key } } --create-dirs -sLo { { item.value } }"
      with_items:
        - {
            key: https://raw.githubusercontent.com/dracula/kitty/master/dracula.conf,
            value: "~/.config/kitty/dracula.conf",
          }
        - {
            key: https://raw.githubusercontent.com/dracula/kitty/master/diff.conf,
            value: "~/.config/kitty/diff.conf",
          }

- name: Create a new Work user
  user:
    name: Work
    password: { { work_user_passwd } }
    shell: { { fish_shell_path } }
