---
- name: Create a user for work related usage.
  user:
    name: Work
    comment: user for work related usage
    password: "$6$HEu.SbtXrbKF2kLj$v3CWlQH0uI/ZW3EnOgrXmPXB7aEWaBhZXes0vaOXuLfeF.KkrGOUxNMzzvLkciNjRtK4dXmtiYOgQ/E5yS9D2/"
    shell: /bin/fish
    state: present

- name: Night Light settings
  block:
    - name: Enable Night Light
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: true
        state: present

    - name: Set Night Light Temperature
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
        value: uint32 4991
        state: present

    - name: Set Night Light Schedule From
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-from
        value: "18"
        state: present

    - name: Set Night Light Schedule To
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-to
        value: "7"
        state: present

- name: Add Slack and GNOME Pomodoro to autostart.
  copy:
    src: { { item } }
    dest: { { autostart_dir } }
  with_items:
    - files/com.slack.Slack.desktop
    - files/org.gnome.Pomodoro.desktop

- name: Copy .gitconfig to user's home directory
  copy:
    src: files/gitconfig
    dest: "{ { home_dir } }/.gitconfig"

- name: Install argonaut theme for tilix
  command: wget -qO ~/.config/tilix/schemes/argonaut.json https://git.io/v7QV5

- name: Clear GNOME tracker cache file
  file:
    path: ~/.cache/tracker
    state: absent

- name: Install Starship
  command: "curl -fsSL https://starship.rs/install.sh | sudo bash"

- name: Change user shell to Fish
  become: true
  user:
    name: { { user } }
    shell: { { fish_shell_path } }

- name: config imwheel
  block:
    copy:
      src: "files/imwheel.service"
      dest: { { systemd_dir } }

    name: reload systemd configuration
    systemd:
      daemon_reload: yes

- name: Install JetBrains Mono Font
  block:
    get_url: >
      url= { { jetbrains_mono_url } }
      dest=/tmp/jetbrains-mono.zip

    unarchive:
      src: /tmp/jetbrains-mono.zip
      dest: /usr/share/fonts/
      remote_src: yes

    command: fc-cache -v
