set -gx GOPATH $HOME/go

starship init fish | source

alias python "python3"

abbr sd "sudo dnf install -y"
abbr update "sudo dnf update"
abbr v "vim"
abbr gcom "git commit -m"
abbr gc "git clone"
abbr gch "git checkout"
abbr gm "git merge"
abbr ga "git add"
abbr gpo "git push origin"
abbr gpom "git push origin master"
abbr gst "git status"
abbr tf "terraform"
abbr tfi "terraform init"
abbr tfp "terraform plan"
abbr tfa "terraform apply"
abbr tfd "terraform destroy"
abbr tfr "terraform refresh"
abbr dk "docker"
abbr dkr "docker run"
abbr dkb "docker build"
abbr dks "docker start"
abbr dkst "docker stop"
abbr dkp "docker pull"
abbr dkps "docker ps"
abbr dki "docker images"
abbr dkc "docker-compose"
abbr dkcu "docker-compose up"
abbr tmas "tmux attach-session -t"
abbr tmls "tmux ls"
abbr tmnew "tmux new -s"
abbr tmkill "tmux kill-session -t"
abbr xcs "xclip -sel clip"
abbr ssc "sudo systemctl"
abbr ssce "sudo systemctl enable"
abbr sscs "sudo systemctl start"
abbr finds "find ~ -name"
abbr findfile "find -type f ~ -name"
abbr finddir "find -type d ~ -name"
abbr findpwd "find . -name"
abbr findroot "find / -name"
abbr py "python"
abbr py2 "python2"
abbr wcp "wl-copy"
abbr wps "wl-paste"
abbr vgi "vagrant init"
abbr vgup "vagrant up"
abbr vgh "vagrant halt"
abbr vgd "vagrant destroy -f"
abbr vgssh "vagrant ssh"
abbr py "python"
